server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.249.42:3306/demo?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  thymeleaf:
    encoding: utf-8
    suffix: .html
    cache: false
  redis:
    host: 47.107.249.42
    timeout: 500
    port: 6376